# Generated by Django 4.2 on 2023-04-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="status",
            field=models.IntegerField(default=1),
        ),
    ]
